#########################################################################
# Title:            Sandbox: InvoiceNinja v5 app                        #
# Author(s):        addbee                                              #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: MariaDB Role
  ansible.builtin.include_role:
    name: mariadb

- name: MariaDB | Create ninja database
  community.mysql.mysql_db:
    name: "invoiceninjav5db"
    login_host: "mariadb"
    login_user: "root"
    login_password: "{{ mariadb_docker_env_password }}"
    state: present

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

# - name: Create directories
#   ansible.builtin.file:
#     path: "{{ item }}"
#     state: directory
#     owner: "1500"
#     group: "invoiceninja"
#     mode: "0775"
#     recurse: true
#   with_items: "{{ lookup('vars', role_name + '_paths_folders_list') }}"

- name: "Settings | Import in-vhost.conf"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: '{{ invoiceninjav5_paths_location }}/{{ item }}'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0664"
    force: yes
  loop:
    - "in-vhost.conf"
    - "php-cli.ini"
    - "php.ini"
  when: invoiceninjav5_overwrite_nginx_config

- name: Remove existing legacy Nginx container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    _var_prefix: "invoiceninja_nginx"

- name: "Execute nginx role"
  ansible.builtin.include_role:
    name: nginx
  vars:
    nginx_docker_image: "nginx:latest"
    nginx_paths_folder: ""
    nginx_paths_folders_list: []
    nginx_web_subdomain: "{{ invoiceninjav5_nginx_web_subdomain }}"
    nginx_web_domain: "{{ invoiceninjav5_nginx_web_domain }}"
    nginx_dns_record: "{{ invoiceninjav5_nginx_dns_record }}"
    nginx_dns_zone: "{{ invoiceninjav5_nginx_dns_zone }}"
    nginx_dns_proxy: "{{ invoiceninjav5_nginx_dns_proxy }}"
    nginx_instances: ["invoiceninja-nginx"]
    nginx_traefik_gzip_enabled: false
    nginx_docker_volumes_default:
      - "{{ invoiceninjav5_paths_location }}/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro"
      - "{{ invoiceninjav5_paths_location }}/public:/var/www/app/public:ro"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
